// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBob8IO3qIx83_OKiy2LIAS_schQBarWRM',
    appId: '1:764579811073:web:d64d12dec93de9a1009500',
    messagingSenderId: '764579811073',
    projectId: 'health-tech-a7191',
    authDomain: 'health-tech-a7191.firebaseapp.com',
    storageBucket: 'health-tech-a7191.firebasestorage.app',
    measurementId: 'G-M6DEDJH7HR',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Y8CHFgYzA3w-Wolr2EHTpMoK4qJFd0U',
    appId: '1:764579811073:ios:bde57deda51633d1009500',
    messagingSenderId: '764579811073',
    projectId: 'health-tech-a7191',
    storageBucket: 'health-tech-a7191.firebasestorage.app',
    iosBundleId: 'com.example.healthTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Y8CHFgYzA3w-Wolr2EHTpMoK4qJFd0U',
    appId: '1:764579811073:ios:bde57deda51633d1009500',
    messagingSenderId: '764579811073',
    projectId: 'health-tech-a7191',
    storageBucket: 'health-tech-a7191.firebasestorage.app',
    iosBundleId: 'com.example.healthTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBob8IO3qIx83_OKiy2LIAS_schQBarWRM',
    appId: '1:764579811073:web:82b8b55bfdebf91d009500',
    messagingSenderId: '764579811073',
    projectId: 'health-tech-a7191',
    authDomain: 'health-tech-a7191.firebaseapp.com',
    storageBucket: 'health-tech-a7191.firebasestorage.app',
    measurementId: 'G-TDB5XHHW1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzwBvtjcXjdwa7jo61MuOl-6cT1j9s0aE',
    appId: '1:764579811073:android:46cd2060ef582d86009500',
    messagingSenderId: '764579811073',
    projectId: 'health-tech-a7191',
    storageBucket: 'health-tech-a7191.firebasestorage.app',
  );

}